/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.modern.instancer.gui;

import com.modern.instancer.data.InstanceOffsetTree;

/**
 *
 * @author kevinlawrence
 */
public class InstanceManagerPanel extends javax.swing.JPanel {

    private InstanceOffsetTree instanceOffsetTree;
    
    private boolean loadInstanceData(){
        
        
        return true;
    }
    
    
    
    
    /**
     * Creates new form InstanceManagerPanel
     */
    public InstanceManagerPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlInstanceTree = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtreeOffsetInstance = new javax.swing.JTree();

        jScrollPane1.setViewportView(jtreeOffsetInstance);

        javax.swing.GroupLayout jpnlInstanceTreeLayout = new javax.swing.GroupLayout(jpnlInstanceTree);
        jpnlInstanceTree.setLayout(jpnlInstanceTreeLayout);
        jpnlInstanceTreeLayout.setHorizontalGroup(
            jpnlInstanceTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        jpnlInstanceTreeLayout.setVerticalGroup(
            jpnlInstanceTreeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlInstanceTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlInstanceTree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnlInstanceTree;
    private javax.swing.JTree jtreeOffsetInstance;
    // End of variables declaration//GEN-END:variables
}
