/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.modern.instancer.gui;

import com.modern.instancer.common.Library;
import com.modern.instancer.data.MemoryFile;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFrame;

/**
 *
 * @author kevinlawrence
 */
public class InstancerMain extends javax.swing.JFrame {
    
    //<editor-fold defaultstate="collapsed" desc="Key Listener">
    private class SketchPadKeyListener implements KeyListener {

        @Override
        public void keyTyped(KeyEvent e) {
//            System.out.println("Key Typed");
        }

        @Override
        public void keyPressed(KeyEvent e) {
            
            System.out.println("Key Pressed");
            switch (e.getKeyCode()) {
                case KeyEvent.VK_1:
                    break;
            }

            if (e.isControlDown()) {
                switch (e.getKeyCode()) {
                    case KeyEvent.VK_G:
                        break;
            
                    case KeyEvent.VK_O:
//                        SketchIO.openFile();
                        break;
                        
                    case KeyEvent.VK_S:
//                        SketchIO.saveToFile(sketchPad.sketchObjects);
                        break;
                }
            }
        }

        @Override
        public void keyReleased(KeyEvent e) {
//            System.out.println("Key Released");
        }
    }
//</editor-fold>

    private class TextEditorListener implements TextEditorEventListenerIntf {

        public TextEditorListener(){};
        
        @Override
        public void handleProcessedFile(MemoryFile file) {
            handleInformationFile(file);
        }  
    }
    
    TextEditorListener gCodeEditorListener;
    
    private void handleInformationFile(MemoryFile infoFile){
        right.setFile(infoFile);
    }

//<editor-fold defaultstate="collapsed" desc="Properties">
    TextEditorPanel left, right;
    
//</editor-fold>
    
    private void internalInit(){
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        left = new TextEditorPanel();
        gCodeEditorListener = new TextEditorListener();
        left.setEventListener(gCodeEditorListener);
        
        right = new TextEditorPanel();
        
        jsplitpnlTextEditor.setLeftComponent(left);
        jsplitpnlTextEditor.setRightComponent(right);
        
        jsplitpnlTextEditor.setDividerLocation(0.5);
    }
    
    @Override
    public void setVisible(boolean visible){
        super.setVisible(visible);
        jsplitpnlTextEditor.setDividerLocation(0.5);
        repaint();
        
        WorkshiftParentChildManagerDialog dlg = new WorkshiftParentChildManagerDialog(this, true);
        dlg.setVisible(true);
    }
    
    
    /**
     * Creates new form InstancerMain
     */
    public InstancerMain() {
        initComponents();
        internalInit();
        
        setIconImage(Library.loadImageFromResource("com/modern/instancer/gui/instancer_icon_250x250.jpg"));
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jsplitpnlTextEditor = new javax.swing.JSplitPane();
        jmbMain = new javax.swing.JMenuBar();
        jmenuFile = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jsplitpnlTextEditor.setDividerLocation(350);

        jmenuFile.setText("File");
        jmbMain.add(jmenuFile);

        jMenu2.setText("Edit");
        jmbMain.add(jMenu2);

        setJMenuBar(jmbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsplitpnlTextEditor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jsplitpnlTextEditor, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InstancerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InstancerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InstancerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstancerMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InstancerMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jmbMain;
    private javax.swing.JMenu jmenuFile;
    private javax.swing.JSplitPane jsplitpnlTextEditor;
    // End of variables declaration//GEN-END:variables
}
