/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.modern.instancer.gui;

import javax.swing.JOptionPane;

/**
 *
 * @author kevinlawrence
 */
public final class InstanceConfigurationEditor extends javax.swing.JPanel {

//<editor-fold defaultstate="collapsed" desc="Constructor & Factory">
    /**
     * Creates new form InstanceConfigurationEditor
     *
     * @param instanceCount
     * @param retraction
     */
    public InstanceConfigurationEditor(int instanceCount, String retraction) {
        initComponents();

        setInstanceCount(instanceCount);
        setRetraction(retraction);
    }

    public static InstanceConfigurationResultIntf showInstanceConfigurationEditor() {
        return showInstanceConfigurationEditor(1, "");
    }

    public static InstanceConfigurationResultIntf showInstanceConfigurationEditor(int instanceCount, String retraction) {
        InstanceConfigurationEditor editorPanel = new InstanceConfigurationEditor(instanceCount, retraction);

        int result = JOptionPane.showConfirmDialog(null, editorPanel, "Instance Configuration", JOptionPane.OK_CANCEL_OPTION);
        return new InstanceConfigurationResult(result, editorPanel.getInstanceCount(), editorPanel.getRetraction());
    }
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="InstanceConfigurationResultIntf">
    public interface InstanceConfigurationResultIntf {

        public int getDialogResult();

        public int getInstanceCount();

        public String getRetraction();
    }

    public static class InstanceConfigurationResult implements InstanceConfigurationResultIntf {

        //<editor-fold defaultstate="collapsed" desc="Constructor">
        public InstanceConfigurationResult(int dialogResult, int instanceCount, String retraction) {
            this.dialogResult = dialogResult;

            this.instanceCount = instanceCount;
            this.retraction = retraction;
        }
        //</editor-fold>

        //<editor-fold defaultstate="collapsed" desc="Properties">
        private final int dialogResult;
        private final int instanceCount;
        private final String retraction;

        /**
         * @return the dialogResult
         */
        @Override
        public int getDialogResult() {
            return dialogResult;
        }

        /**
         * @return the instanceCount
         */
        @Override
        public int getInstanceCount() {
            return instanceCount;
        }

        /**
         * @return the retraction
         */
        @Override
        public String getRetraction() {
            return retraction;
        }
        //</editor-fold>
    }
    //</editor-fold>     

//<editor-fold defaultstate="collapsed" desc="Properties">
    private int instanceCount;
    private String retraction;

    /**
     * @return the instanceCount
     */
    public int getInstanceCount() {
        return (int) jspinInstanceCount.getValue();
    }

    /**
     * @param instanceCount the instanceCount to set
     */
    public void setInstanceCount(int instanceCount) {
        jspinInstanceCount.setValue(instanceCount);
    }

    /**
     * @return the retraction
     */
    public String getRetraction() {
        return jtxtRetraction.getText();
    }

    /**
     * @param retraction the retraction to set
     */
    public void setRetraction(String retraction) {
        jtxtRetraction.setText(retraction);
    }
//</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblInstances = new javax.swing.JLabel();
        jlblRetraction = new javax.swing.JLabel();
        jtxtRetraction = new javax.swing.JTextField();
        jspinInstanceCount = new javax.swing.JSpinner();

        jlblInstances.setText("Number of copies (instances)");

        jlblRetraction.setText("Intra-instance retraction");

        jspinInstanceCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblInstances, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblRetraction))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jspinInstanceCount, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .addComponent(jtxtRetraction))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblInstances)
                    .addComponent(jspinInstanceCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblRetraction)
                    .addComponent(jtxtRetraction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblInstances;
    private javax.swing.JLabel jlblRetraction;
    private javax.swing.JSpinner jspinInstanceCount;
    private javax.swing.JTextField jtxtRetraction;
    // End of variables declaration//GEN-END:variables
}
