/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.modern.instancer.gui;

import com.modern.instancer.data.Workshift;
import com.modern.instancer.data.WorkshiftListProviderIntf;

/**
 *
 * @author kevinlawrence
 */
public final class WorkshiftEditorDialog extends javax.swing.JDialog {

//<editor-fold defaultstate="collapsed" desc="Properties">
    private Workshift workshift;
    private WorkshiftListProviderIntf workshiftListProvider;
    private final WorkshiftUpdateHandlerIntf updateHandler;

    /**
     * @return the workshift
     */
    public Workshift getWorkshift() {
        return workshift;
    }

    /**
     * @param workshift the workshift to set
     */
    public void setWorkshift(Workshift workshift) {
        this.workshift = workshift;
        updateOffsetDisplay();
    }

    /**
     * @param workshiftListProvider the workshiftListProvider to set
     */
    public void setWorkshiftListProvider(WorkshiftListProviderIntf workshiftListProvider) {
        this.workshiftListProvider = workshiftListProvider;
        updateWorkshiftListDisplay();
    }
//</editor-fold>
    
//<editor-fold defaultstate="collapsed" desc="Data Update Methods">
    public void updateWorkshiftListNavigation() {
        jbtnPreviousOriginalOffset.setEnabled(jcbxOriginalOffset.getItemCount() > 0);
        jbtnNextOriginalOffset.setEnabled(jcbxOriginalOffset.getItemCount() > 0);
        
        //TODO: remove out later
        jbtnPreviousOriginalOffset.setVisible(false);
        jbtnNextOriginalOffset.setVisible(false);
    }
    
    public void updateWorkshiftListDisplay() {
        //setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbxOriginalOffset.removeAllItems();
        
        if (workshiftListProvider != null) {
            workshiftListProvider.getWorkshiftIDsSorted().stream().forEachOrdered(offsetID -> jcbxOriginalOffset.addItem(offsetID));
        }
        updateWorkshiftListNavigation();
    }
    
    public void updateOffsetDisplay() {
        jtxtBaseName.setText("");
        jcbx180DegreeRotation.setSelected(false);
        
        if (workshift != null) {
            this.setTitle(workshift.getWorkshiftID());
            
            jtxtBaseName.setText(workshift.getNameBase());
            jspinInstance.setValue(workshift.getInstance());
            jcbx180DegreeRotation.setSelected(workshift.isRotate180Degrees());
        }
    }
    
    public void updateOffsetData() {
        if (workshift != null) {
            workshift.setNameBase(jtxtBaseName.getText());
            workshift.setInstance((int) jspinInstance.getValue());
            workshift.setRotate180Degrees(jcbx180DegreeRotation.isSelected());
            
            //TODO... do we even want to allow this?
            //offset.setParentOffsetID((String) jcbxOriginalOffset.getSelectedItem());
        }
    }
//</editor-fold>

    /**
     * Creates new form OffsetEditorDialog
     * @param parent
     * @param modal
     * @param offset
     * @param updateHandler
     */
    public WorkshiftEditorDialog(java.awt.Frame parent, boolean modal, Workshift offset, WorkshiftUpdateHandlerIntf updateHandler) {
        super(parent, modal);
        initComponents();
        
        this.workshift = offset;
        this.updateHandler = updateHandler;

        updateWorkshiftListNavigation();
        updateOffsetDisplay();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlLogo = new javax.swing.JPanel();
        jlblModernLogo = new javax.swing.JLabel();
        jpnlControls = new javax.swing.JPanel();
        jbtnAccept = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();
        jpnlOffset = new javax.swing.JPanel();
        jpnlParentOffset = new javax.swing.JPanel();
        lblOriginalOffset = new javax.swing.JLabel();
        jcbxOriginalOffset = new javax.swing.JComboBox<>();
        jbtnPreviousOriginalOffset = new javax.swing.JButton();
        jbtnNextOriginalOffset = new javax.swing.JButton();
        jpnlOffsetInstance = new javax.swing.JPanel();
        jlblOffsetInstanceID = new javax.swing.JLabel();
        jtxtBaseName = new javax.swing.JTextField();
        jcbx180DegreeRotation = new javax.swing.JCheckBox();
        jspinInstance = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnlLogo.setBackground(new java.awt.Color(0, 153, 255));

        jlblModernLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/modern/instancer/gui/modern_engineering.png"))); // NOI18N

        javax.swing.GroupLayout jpnlLogoLayout = new javax.swing.GroupLayout(jpnlLogo);
        jpnlLogo.setLayout(jpnlLogoLayout);
        jpnlLogoLayout.setHorizontalGroup(
            jpnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlLogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblModernLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        jpnlLogoLayout.setVerticalGroup(
            jpnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlblModernLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jbtnAccept.setText("Accept");
        jbtnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAcceptActionPerformed(evt);
            }
        });

        jbtnCancel.setText("Cancel");
        jbtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlControlsLayout = new javax.swing.GroupLayout(jpnlControls);
        jpnlControls.setLayout(jpnlControlsLayout);
        jpnlControlsLayout.setHorizontalGroup(
            jpnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlControlsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlControlsLayout.setVerticalGroup(
            jpnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlControlsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAccept)
                    .addComponent(jbtnCancel)))
        );

        lblOriginalOffset.setText("Parent (Main) Offset ID");

        jcbxOriginalOffset.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnPreviousOriginalOffset.setText("<");
        jbtnPreviousOriginalOffset.setToolTipText("Previous Original Offset");

        jbtnNextOriginalOffset.setText(">");
        jbtnNextOriginalOffset.setToolTipText("Next Original Offset");

        javax.swing.GroupLayout jpnlParentOffsetLayout = new javax.swing.GroupLayout(jpnlParentOffset);
        jpnlParentOffset.setLayout(jpnlParentOffsetLayout);
        jpnlParentOffsetLayout.setHorizontalGroup(
            jpnlParentOffsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlParentOffsetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbxOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnPreviousOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnNextOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jpnlParentOffsetLayout.setVerticalGroup(
            jpnlParentOffsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlParentOffsetLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnlParentOffsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOriginalOffset)
                    .addComponent(jcbxOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnPreviousOriginalOffset)
                    .addComponent(jbtnNextOriginalOffset)))
        );

        jpnlOffsetInstance.setForeground(new java.awt.Color(255, 255, 255));

        jlblOffsetInstanceID.setText("Base / Instance ID");

        jcbx180DegreeRotation.setText("180 Rotation?");

        jspinInstance.setModel(new javax.swing.SpinnerNumberModel(1, 1, 300, 1));

        javax.swing.GroupLayout jpnlOffsetInstanceLayout = new javax.swing.GroupLayout(jpnlOffsetInstance);
        jpnlOffsetInstance.setLayout(jpnlOffsetInstanceLayout);
        jpnlOffsetInstanceLayout.setHorizontalGroup(
            jpnlOffsetInstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlOffsetInstanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblOffsetInstanceID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtBaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspinInstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbx180DegreeRotation)
                .addGap(124, 124, 124))
        );
        jpnlOffsetInstanceLayout.setVerticalGroup(
            jpnlOffsetInstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlOffsetInstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlblOffsetInstanceID)
                .addComponent(jtxtBaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jcbx180DegreeRotation)
                .addComponent(jspinInstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnlOffsetLayout = new javax.swing.GroupLayout(jpnlOffset);
        jpnlOffset.setLayout(jpnlOffsetLayout);
        jpnlOffsetLayout.setHorizontalGroup(
            jpnlOffsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlParentOffset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlOffsetInstance, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
        jpnlOffsetLayout.setVerticalGroup(
            jpnlOffsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlOffsetLayout.createSequentialGroup()
                .addComponent(jpnlParentOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlOffsetInstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlOffset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnlControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 490, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jpnlOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnlControls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jpnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 131, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAcceptActionPerformed
        updateOffsetData();
        if (updateHandler != null) {
            updateHandler.onUpdate(workshift);
        }
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jbtnAcceptActionPerformed

    private void jbtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jbtnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(WorkshiftEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WorkshiftEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WorkshiftEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WorkshiftEditorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                WorkshiftEditorDialog dialog = new WorkshiftEditorDialog(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAccept;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnNextOriginalOffset;
    private javax.swing.JButton jbtnPreviousOriginalOffset;
    private javax.swing.JCheckBox jcbx180DegreeRotation;
    private javax.swing.JComboBox<String> jcbxOriginalOffset;
    private javax.swing.JLabel jlblModernLogo;
    private javax.swing.JLabel jlblOffsetInstanceID;
    private javax.swing.JPanel jpnlControls;
    private javax.swing.JPanel jpnlLogo;
    private javax.swing.JPanel jpnlOffset;
    private javax.swing.JPanel jpnlOffsetInstance;
    private javax.swing.JPanel jpnlParentOffset;
    private javax.swing.JSpinner jspinInstance;
    private javax.swing.JTextField jtxtBaseName;
    private javax.swing.JLabel lblOriginalOffset;
    // End of variables declaration//GEN-END:variables
}
