/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.modern.instancer.gui;

import com.modern.instancer.data.Workshift;
import com.modern.instancer.data.WorkshiftListProviderIntf;

/**
 *
 * @author kevinlawrence
 */
public class WorkshiftInstanceEditorPanel extends javax.swing.JPanel {

//<editor-fold defaultstate="collapsed" desc="Properties">
    private Workshift workshift;
    private WorkshiftListProviderIntf workshiftListProvider;

    /**
     * @return the workshift
     */
    public Workshift getWorkshift() {
        return workshift;
    }

    /**
     * @param workshift the workshift to set
     */
    public void setWorkshift(Workshift workshift) {
        this.workshift = workshift;
        updateWorkshiftDisplay();
    }

    /**
     * @param workshiftListProvider the offsetListProvider to set
     */
    public void setWorkshiftListProvider(WorkshiftListProviderIntf workshiftListProvider) {
        this.workshiftListProvider = workshiftListProvider;
        updateWorkshiftListDisplay();
    }
//</editor-fold>

//<editor-fold defaultstate="collapsed" desc="Data Update Methods">
    public void updateWorkshiftListNavigation() {
        jbtnPreviousOriginalOffset.setEnabled(jcbxOriginalOffset.getItemCount() > 0);
        jbtnNextOriginalOffset.setEnabled(jcbxOriginalOffset.getItemCount() > 0);
        
        //TODO: remove out later
        jbtnPreviousOriginalOffset.setVisible(false);
        jbtnNextOriginalOffset.setVisible(false);
    }
    
    public void updateWorkshiftListDisplay() {
        //setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcbxOriginalOffset.removeAllItems();
        
        if (workshiftListProvider != null) {
            workshiftListProvider.getWorkshiftIDsSorted().stream().forEachOrdered(offsetID -> jcbxOriginalOffset.addItem(offsetID));
        }
        updateWorkshiftListNavigation();
    }
    
    public void updateWorkshiftDisplay() {
        jtxtBaseName.setText("");
        jcbx180DegreeRotation.setSelected(false);
        
        if (workshift != null) {
//            this.s(workshift.getWorkshiftID());
            jtxtBaseName.setText(workshift.getNameBase());
            jspinInstance.setValue(workshift.getInstance());
            jcbx180DegreeRotation.setSelected(workshift.isRotate180Degrees());
        }
    }
    
    public void updateWorkshiftData() {
        if (workshift != null) {
            workshift.setWorkshiftID(jtxtBaseName.getText());
            workshift.setInstance((int) jspinInstance.getValue());
            workshift.setRotate180Degrees(jcbx180DegreeRotation.isSelected());
            //TODO... do we even want to allow this?
            workshift.setParentWorkshiftID((String) jcbxOriginalOffset.getSelectedItem());
        }
    }
//</editor-fold>
    
    /**
     * Creates new form InstanceEditorPanel
     */
    public WorkshiftInstanceEditorPanel(Workshift workshift) {
        initComponents();

        this.workshift = workshift;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlOriginalOffset = new javax.swing.JPanel();
        lblParentWorkshiftID = new javax.swing.JLabel();
        jcbxOriginalOffset = new javax.swing.JComboBox<>();
        jbtnPreviousOriginalOffset = new javax.swing.JButton();
        jbtnNextOriginalOffset = new javax.swing.JButton();
        jpnlOffsetInstance = new javax.swing.JPanel();
        jlblOffsetInstanceID = new javax.swing.JLabel();
        jtxtBaseName = new javax.swing.JTextField();
        jcbx180DegreeRotation = new javax.swing.JCheckBox();
        jspinInstance = new javax.swing.JSpinner();
        jpnlControls = new javax.swing.JPanel();
        jbtnAccept = new javax.swing.JButton();
        jbtnCancel = new javax.swing.JButton();

        lblParentWorkshiftID.setText("Parent (Main) Workshift ID");

        jcbxOriginalOffset.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jbtnPreviousOriginalOffset.setText("<");
        jbtnPreviousOriginalOffset.setToolTipText("Previous Original Offset");

        jbtnNextOriginalOffset.setText(">");
        jbtnNextOriginalOffset.setToolTipText("Next Original Offset");

        javax.swing.GroupLayout jpnlOriginalOffsetLayout = new javax.swing.GroupLayout(jpnlOriginalOffset);
        jpnlOriginalOffset.setLayout(jpnlOriginalOffsetLayout);
        jpnlOriginalOffsetLayout.setHorizontalGroup(
            jpnlOriginalOffsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlOriginalOffsetLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblParentWorkshiftID, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbxOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnPreviousOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnNextOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlOriginalOffsetLayout.setVerticalGroup(
            jpnlOriginalOffsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlOriginalOffsetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlOriginalOffsetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblParentWorkshiftID)
                    .addComponent(jcbxOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnNextOriginalOffset)
                    .addComponent(jbtnPreviousOriginalOffset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnlOffsetInstance.setForeground(new java.awt.Color(255, 255, 255));

        jlblOffsetInstanceID.setText("Transform ID");

        jcbx180DegreeRotation.setText("180 Rotation?");

        jspinInstance.setModel(new javax.swing.SpinnerNumberModel(1, 1, 300, 1));

        javax.swing.GroupLayout jpnlOffsetInstanceLayout = new javax.swing.GroupLayout(jpnlOffsetInstance);
        jpnlOffsetInstance.setLayout(jpnlOffsetInstanceLayout);
        jpnlOffsetInstanceLayout.setHorizontalGroup(
            jpnlOffsetInstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlOffsetInstanceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblOffsetInstanceID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtBaseName, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jspinInstance, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcbx180DegreeRotation, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpnlOffsetInstanceLayout.setVerticalGroup(
            jpnlOffsetInstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlOffsetInstanceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlOffsetInstanceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblOffsetInstanceID)
                    .addComponent(jtxtBaseName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbx180DegreeRotation)
                    .addComponent(jspinInstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnAccept.setText("Accept");

        jbtnCancel.setText("Cancel");

        javax.swing.GroupLayout jpnlControlsLayout = new javax.swing.GroupLayout(jpnlControls);
        jpnlControls.setLayout(jpnlControlsLayout);
        jpnlControlsLayout.setHorizontalGroup(
            jpnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlControlsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbtnCancel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAccept))
        );
        jpnlControlsLayout.setVerticalGroup(
            jpnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlControlsLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jpnlControlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnAccept)
                    .addComponent(jbtnCancel)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlOriginalOffset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlOffsetInstance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnlControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnlOriginalOffset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlOffsetInstance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnlControls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAccept;
    private javax.swing.JButton jbtnCancel;
    private javax.swing.JButton jbtnNextOriginalOffset;
    private javax.swing.JButton jbtnPreviousOriginalOffset;
    private javax.swing.JCheckBox jcbx180DegreeRotation;
    private javax.swing.JComboBox<String> jcbxOriginalOffset;
    private javax.swing.JLabel jlblOffsetInstanceID;
    private javax.swing.JPanel jpnlControls;
    private javax.swing.JPanel jpnlOffsetInstance;
    private javax.swing.JPanel jpnlOriginalOffset;
    private javax.swing.JSpinner jspinInstance;
    private javax.swing.JTextField jtxtBaseName;
    private javax.swing.JLabel lblParentWorkshiftID;
    // End of variables declaration//GEN-END:variables

}
